HW08 is completed step 1
Elyas-Crimean/Otus-go pull request #8
Opened 2023-12-18 19:04 UTC by Elyas-Crimean

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-12-21 14:23 UTC, ityulkanov commented on hw08_envdir_tool/executor.go
> +	command.Stdout = os.Stdout
можно еще err добавить

2023-12-21 17:06 UTC, ityulkanov requested changes
Добрый вечер, Илья. Оставил вам парочку комментариев как можно было бы улучшить ДЗ.

2023-12-21 17:06 UTC, engineer-go commented on hw08_envdir_tool/env_reader.go
> +			continue
тут бы правильнее unsupported file err было возвращать

2023-12-21 17:06 UTC, engineer-go commented on hw08_envdir_tool/env_reader.go
> +			continue
Ну и соответственно везде где есть err - её нужно возвращать а не пропускать. Иначе будет непонятно для пользователя в чём проблема

2023-12-21 17:06 UTC, engineer-go commented on hw08_envdir_tool/executor.go
> +	}
Близко, но кое что пропущено. В идеале было бы не только иметь доступ к переменным которые мы назначаем, но и ко всем переменным среды в которой запускается программа. os.Environ() возвращает эти перменные. Дальше мы можем просто слить systemEnvs и наши сделанные envы, а их уже затолкать в cmd.Env 
returnCode кмк лучше было бы возвращать через command.ProcessState.ExitCode()

2023-12-21 19:00 UTC, Elyas-Crimean commented on hw08_envdir_tool/executor.go
> +	}
исходные переменные среды собираются в main, а не в executor

2023-12-21 19:03 UTC, ityulkanov commented on hw08_envdir_tool/executor.go
> +	}
А, всё, увидел, да, этот комментарий значит удаляем

2023-12-21 19:13 UTC, Elyas-Crimean commented on hw08_envdir_tool/env_reader.go
> +			continue
Это я скорее перестраховлся на ./ ..

2023-12-21 19:15 UTC, Elyas-Crimean commented on hw08_envdir_tool/env_reader.go
> +			continue
Я исходил из того, что лучше обработать, что возможно. При любом неудобстве завершать работу спорно.
Если какойто-файлик не читается, можно и работать с остальными, но это лучше определять явно. 
Уже как-то напрашиваются фатальные/нефатальные ошибки ..., ошибка со списком возможных проблем....

2023-12-21 19:25 UTC, Elyas-Crimean commented on hw08_envdir_tool/executor.go
> +	command.Stdout = os.Stdout
добавил

2023-12-22 08:49 UTC, ityulkanov commented on hw08_envdir_tool/env_reader.go
> +			continue
Ну тут либо список возвращать, и правда, либо сразу ошибку. Иначе что то обработается, что то нет, как потом юзеру понимать что не так?

2024-01-06 08:24 UTC, ityulkanov approved these changes

2024-01-06 08:58 UTC, merged